name: example
description: "Demonstrates how to use the fl_aliyun_number_auth plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_aliyun_number_auth:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true